sudo: false
language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: TOXENV=py27-django111-drf39
    - python: 2.7
      env: TOXENV=py27-django111-drf39

    - python: 3.5
      env: TOXENV=py35-django111-drf39
    - python: 3.5
      env: TOXENV=py35-django20-drf39
    - python: 3.5
      env: TOXENV=py35-django21-drf39
    - python: 3.6
      env: TOXENV=py35-django22-drf39
    - python: 3.5
      env: TOXENV=py35-djangomaster-drf39

    - python: 3.6
      env: TOXENV=py36-django111-drf39
    - python: 3.6
      env: TOXENV=py36-django20-drf39
    - python: 3.6
      env: TOXENV=py36-django21-drf39
    - python: 3.6
      env: TOXENV=py36-django22-drf39
    - python: 3.6
      env: TOXENV=py36-djangomaster-drf39

    - python: 3.7
      env: TOXENV=py37-django111-drf39
    - python: 3.7
      env: TOXENV=py37-django20-drf39
    - python: 3.7
      env: TOXENV=py37-django21-drf39
    - python: 3.7
      env: TOXENV=py37-django22-drf39
    - python: 3.7
      env: TOXENV=py37-djangomaster-drf39

install:
  - travis_retry pip install -U tox-travis

script:
  - tox

after_success:
  - travis_retry pip install -U codecov
  - codecov
